# Generated by Django 3.1.5 on 2021-06-05 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=20)),
                ('account', models.BigIntegerField()),
                ('ifsc_code', models.CharField(max_length=20)),
                ('mainbalance', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=500)),
                ('cplace', models.CharField(max_length=500)),
                ('cpin', models.CharField(max_length=500)),
                ('cemail', models.CharField(max_length=500)),
                ('cphone', models.BigIntegerField()),
                ('cphoto', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='freelancers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=500)),
                ('fplace', models.CharField(max_length=500)),
                ('fpost', models.CharField(max_length=500)),
                ('fpin', models.IntegerField()),
                ('femail', models.CharField(max_length=500)),
                ('fcontact', models.CharField(max_length=500)),
                ('fexperiance', models.CharField(max_length=500)),
                ('fphoto', models.CharField(max_length=500)),
                ('skill', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('types', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='requiredservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('clogin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.client')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=500)),
                ('service_details', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=500)),
                ('flogin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancers')),
            ],
        ),
        migrations.CreateModel(
            name='service_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateField()),
                ('status', models.CharField(max_length=500)),
                ('clogin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.client')),
                ('serviceid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.service')),
            ],
        ),
        migrations.CreateModel(
            name='requiredservicestat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flogin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancers')),
                ('rsid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.requiredservice')),
            ],
        ),
        migrations.CreateModel(
            name='notification_f',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=500)),
                ('notification', models.CharField(max_length=500)),
                ('ndate', models.DateField()),
                ('nfreelancerid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancers')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=500)),
                ('notification', models.CharField(max_length=500)),
                ('ndate', models.DateField()),
                ('nclientid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.client')),
            ],
        ),
        migrations.AddField(
            model_name='freelancers',
            name='flogin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.login'),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500)),
                ('feedback_date', models.DateField()),
                ('serreqid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.service_request')),
            ],
        ),
        migrations.CreateModel(
            name='fcomplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=500)),
                ('cdate', models.DateField()),
                ('replay', models.CharField(max_length=500)),
                ('replaydate', models.DateField()),
                ('fl_loginid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancers')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='clogin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.login'),
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('chat_date', models.DateField()),
                ('clogin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.client')),
                ('flogin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.login')),
            ],
        ),
        migrations.CreateModel(
            name='ccomplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=500)),
                ('cdate', models.DateField()),
                ('replay', models.CharField(max_length=500)),
                ('replaydate', models.DateField()),
                ('clogin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='freelancer.client')),
            ],
        ),

        migrations.CreateModel(
            name='chat1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.IntegerField()),
                ('sender', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
                ('chat_date', models.DateField()),
            ],
        ),
    ]
