# Generated by Django 3.1.5 on 2021-06-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.IntegerField()),
                ('sender', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
                ('chat_date', models.DateField()),
            ],
        ),
    ]
